@file:Suppress("unused")

package no1.payamax.services

import android.database.Cursor

class PayamakColumns(cursor: Cursor) {
    val idIndex = cursor.getColumnIndex("_id")
    val threadIdIndex = cursor.getColumnIndex("thread_id")
    val addressIndex = cursor.getColumnIndex("address")
    val personIndex = cursor.getColumnIndex("person")
    val dateIndex = cursor.getColumnIndex("date")
    val sentDateIndex = cursor.getColumnIndex("date_sent")
    val protocolIndex = cursor.getColumnIndex("protocol")
    val readIndex = cursor.getColumnIndex("read")
    val statusIndex = cursor.getColumnIndex("status")
    val typeIndex = cursor.getColumnIndex("type")
    val replyPathPresentIndex = cursor.getColumnIndex("reply_path_present")
    val subjectIndex = cursor.getColumnIndex("subject")
    val bodyIndex = cursor.getColumnIndex("body")
    val serviceCenterIndex = cursor.getColumnIndex("service_center")
    val lockedIndex = cursor.getColumnIndex("locked")
    val errorCodeIndex = cursor.getColumnIndex("error_code")
    val subIdIndex = cursor.getColumnIndex("sub_id")
    val creatorIndex = cursor.getColumnIndex("creator")
    val seenIndex = cursor.getColumnIndex("seen")
    val deletableIndex = cursor.getColumnIndex("deletable")
    val simSlotIndex = cursor.getColumnIndex("sim_slot")
    val simImsiIndex = cursor.getColumnIndex("sim_imsi")
    val hiddenIndex = cursor.getColumnIndex("hidden")
    val groupIdIndex = cursor.getColumnIndex("group_id")
    val groupTypeIndex = cursor.getColumnIndex("group_type")
    val deliveryDateIndex = cursor.getColumnIndex("delivery_date")
    val appIdIndex = cursor.getColumnIndex("app_id")
    val msgIdIndex = cursor.getColumnIndex("msg_id")
    val callbackNumberIndex = cursor.getColumnIndex("callback_number")
    val reservedIndex = cursor.getColumnIndex("reserved")
    val priIndex = cursor.getColumnIndex("pri")
    val teleserviceIdIndex = cursor.getColumnIndex("teleservice_id")
    val linkUrlIndex = cursor.getColumnIndex("link_url")
    val svcCmdIndex = cursor.getColumnIndex("svc_cmd")
    val svcCmdContentIndex = cursor.getColumnIndex("svc_cmd_content")
    val roamPendingIndex = cursor.getColumnIndex("roam_pending")
    val spamReportIndex = cursor.getColumnIndex("spam_report")
    val secretModeIndex = cursor.getColumnIndex("secret_mode")
    val safeMessageIndex = cursor.getColumnIndex("safe_message")
    val favoriteIndex = cursor.getColumnIndex("favorite")
    val dRptCntIndex = cursor.getColumnIndex("d_rpt_cnt")
    val usingModeIndex = cursor.getColumnIndex("using_mode")
    val fromAddressIndex = cursor.getColumnIndex("from_address")
    val announcementsSubtypeIndex = cursor.getColumnIndex("announcements_subtype")
    val announcementsScenarioIdIndex = cursor.getColumnIndex("announcements_scenario_id")
    val deviceNameIndex = cursor.getColumnIndex("device_name")
    val correlationTagIndex = cursor.getColumnIndex("correlation_tag")
    val objectIdIndex = cursor.getColumnIndex("object_id")
    val cmcPropIndex = cursor.getColumnIndex("cmc_prop")
    val binInfoIndex = cursor.getColumnIndex("bin_info")
    val reOriginalBodyIndex = cursor.getColumnIndex("re_original_body")
    val reBodyIndex = cursor.getColumnIndex("re_body")
    val reOriginalKeyIndex = cursor.getColumnIndex("re_original_key")
    val reRecipientAddressIndex = cursor.getColumnIndex("re_recipient_address")
    val reContentUriIndex = cursor.getColumnIndex("re_content_uri")
    val reContentTypeIndex = cursor.getColumnIndex("re_content_type")
    val reFileNameIndex = cursor.getColumnIndex("re_file_name")
    val reTypeIndex = cursor.getColumnIndex("re_type")
    val reCountInfoIndex = cursor.getColumnIndex("re_count_info")
}